site_name: 'TB-Profiler'
docs_dir: '../../docs/pt'                  
site_dir: '../../build/pt'                 

repo_url: https://github.com/jodyphelan/TBProfiler


theme:
  name: material
  language: pt
extra:
  alternate:
    - name: English
      link: https://jodyphelan.github.io/TBProfiler/
      lang: en
    - name: Português
      link: https://jodyphelan.github.io/TBProfiler/pt/
      lang: pt