site_name: 'TB-Profiler'
docs_dir: '../../docs/pt'                           # Where to find the English markdown files
site_dir: '../../build/pt'                      # Where to put the English HTML files

theme:
  name: material
  language: pt
extra:
  alternate:
    - name: English
      link: https://jodyphelan.github.io/TBProfiler/en/
      lang: en
    - name: Português
      link: https://jodyphelan.github.io/TBProfiler/pt/
      lang: pt